export const LOGIN_USERS_START = "LOGIN_USERS_START";
export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS";
export const LOGIN_USERS_ERROR = "LOGIN_USERS_ERROR ";

export const CREATE_USERS_START = "CREATE_USERS_START ";
export const CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS ";
export const CREATE_USERS_ERROR = "CREATE_USERS_ERROR ";

export const DELETE_USERS_START = "DELETE_USERS_START ";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS ";
export const DELETE_USERS_ERROR = "DELETE_USERS_ERROR ";

export const UPDATE_USERS_START = "UPDATE_USERS_START ";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS ";
export const UPDATE_USERS_ERROR = "UPDATE_USERS_ERROR ";

export const UPLOAD_IMG_START = "UPLOAD_IMG_START ";
export const UPLOAD_IMG_SUCCESS = "UPLOAD_IMG_SUCCESS ";
export const UPLOAD_IMG_ERROR = "UPLOAD_IMG_ERROR ";

// IMAGES & files Name UPLOADS START =====>

export const IMG_FILE_NAME_GET_START = "IMG_FILE_NAME_GET_START";
export const IMG_FILE_NAME_GET_SUCCESS = "IMG_FILE_NAME_GET_SUCCESS";
export const IMG_FILE_NAME_GET_ERROR = "IMG_FILE_NAME_GET_ERROR ";

export const IMG_FILE_NAME_POST_START = "IMG_FILE_NAME_POST_START";
export const IMG_FILE_NAME_POST_SUCCESS = "IMG_FILE_NAME_POST_SUCCESS";
export const IMG_FILE_NAME_POST_ERROR = "IMG_FILE_NAME_POST_ERROR ";

export const IMG_FILE_NAME_DELETE_START = "IMG_FILE_NAME_DELETE_START ";
export const IMG_FILE_NAME_DELETE_SUCCESS = "IMG_FILE_NAME_DELETE_SUCCESS ";
export const IMG_FILE_NAME_DELETE_ERROR = "IMG_FILE_NAME_DELETE_ERROR ";

export const IMG_FILE_NAME_UPDATE_START = "IMG_FILE_NAME_UPDATE_START ";
export const IMG_FILE_NAME_UPDATE_SUCCESS = "IMG_FILE_NAME_UPDATE_SUCCESS ";
export const IMG_FILE_NAME_UPDATE_ERROR = "IMG_FILE_NAME_UPDATE_ERROR ";

// IMAGES UPLOADS & Files Name END =====>
